### ISSUE TITLE
Renderer parameters for color reconstruction

### ISSUE THREAD

**Issue by sunshineatnoon** [ShichenLiu/SoftRas#10]
Hi, Thanks for open-sourcing this awesome project. For the image reconstruction part, may I ask what parameters you use in the renderer? (gamma_val, aggr_func_rgb etc.). Also, would you please shed some light on why we need to aggregate all faces when computing color? Cause it seems only the face with the smallest z matters to color.

**Comment by ShichenLiu** [comment]
Hi,

I just uploaded shape recon code. Please check in the code!
When compute gradient from color to texture, I would agree that only the front triangle matters. However, when computing gradient to vertices, the color from other triangles also matters so that the vertices would know where they should "move" to match the ground truth images.

**Comment by sunshineatnoon** [comment]
Thanks!

**Comment by tejank10** [comment]
Hi @sunshineatnoon, were you able to reproduce the color reconstruction experiment?
