### ISSUE TITLE
rendering glitches

### ISSUE THREAD

**Issue by flixpar** [ShichenLiu/SoftRas#12]
I'm working on a project where I need to find optimal camera parameters, but I am getting some strange rendering artifacts when I try to use this renderer from some viewpoints.

Good:
![good](https://user-images.githubusercontent.com/7800561/62483842-b1eb4f80-b786-11e9-8965-898020a44309.png)

Bad:
![near](https://user-images.githubusercontent.com/7800561/62483846-b4e64000-b786-11e9-91c0-d973c57db64a.png)
![angle](https://user-images.githubusercontent.com/7800561/62483848-b6176d00-b786-11e9-961c-6fa4244d3d42.png)
![other](https://user-images.githubusercontent.com/7800561/62483850-b7489a00-b786-11e9-8582-e9ad0d59ad54.png)

These glitches do not appear when I view the mesh in MeshLab.

Here is a zip of the files needed to reproduce this issue: [test.zip](https://github.com/ShichenLiu/SoftRas/files/3468738/test.zip)

I've been working on this for a few days but can't figure out what the problem is. Do you have any ideas about what could be causing this?

**Comment by ShichenLiu** [comment]
Hi flixpar,

Can you describe more about the "glitches"? I assume you mean the parts where the cubes intersect with the floor (dark blue and purple). I suppose this is because our soft formulation of rasterization will produce "smooth" transition of color even with very small sigma and gamma (very likely due to numerical issue). And since it is an approximation of traditional renderer, there might be some difference (between OpenGL render and SoftRas). I would regard these glitches as a normal behavior of SoftRas.
