### ISSUE TITLE
Code requires Nueral Renderal package, but I think it is typo

### ISSUE THREAD

**Issue by mks0601** [ShichenLiu/SoftRas#2]
Hi, I installed the code and run demo, however it required neural_renderer package in `soft_renderer/functional/load_obj.py, line 7`. I modified it to `soft_renderer.cuda.load_textures as load_textures_cuda` and it worked. 

Also, maybe it would be better to include gcc related things in your README. Current CUDA (even 10.0) does not support gcc8 but latest OS (I'm using latest Fedora) use gcc8 as default compiler. I manually installed gcc7 and added soft link to enforce my machine use gcc7 as default compiler. After changing to gcc7, it worked.

**Comment by ShichenLiu** [comment]
Hi,

Thanks for checking the typo, since our code is built from neural_renderer, this is a typo. I have modified the code. I used ubuntu so there was no gcc error on my side. I will test for other environment to see if there are problems. Also the compilation of CUDS is instructed by PyTorch documentation (https://pytorch.org/tutorials/advanced/cpp_extension.html), I will also check the docs to see if there are any other environment requirements.
